apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: game-app-rc
  labels:
    app: mygame-app
spec:
  template:
    metadata: 
      name: game-app-pod
      labels:
        app: mygame-app
    spec:
      containers:
        
